files:
  - source: /librecad/ts/librecad_en.ts
    translation: /librecad/ts/librecad_%locale_with_underscore%.ts
  - source: /plugins/ts/plugins_en.ts
    translation: /plugins/ts/plugins_%locale_with_underscore%.ts
